#!/usr/bin/env bash
# Script to tansfer file from localhost to remote server
# "$#" in bash counts the arguments passed
# -lt stands for less than
# scp (Secure copy) transfers file to and from remote server and local host
# -o checks pass options to ssh in the format used in ssh_config(5)
# StrickHostKeyChecking specifies how host keys are checked
# Selects the file from which the identity (private key) for
#	public key authentication is read

if [ "$#" -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
