#!/usr/bin/env bash
# Script to innstall enginx on server
# This script should be run on the server itself

sudo apt-get  update -y
sudo apt-get install nginx -y
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
