#!/usr/bin/env bash
# Script to innstall enginx on server
# This script should be run on the server itself

apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start
