#!/usr/bin/env bash
# Script to innstall enginx on server
# This script should be run on the server itself

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
